server:
  port: 8765

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://43.241.63.102:8888

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**,/role/**,/authenticate,/validate,/refresh

        - id: MASTER-SERVICE
          uri: lb://MASTER-SERVICE
          predicates:
            - Path=/class/**,/region/**,/school/**,/educationalInstitution/**,/student/**

        - id: REPORT-SERVICE
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/class/**,/region/**,/school/**,/educationalInstitution/**,/student/**