server:
  port: 8765
  address: 0.0.0.0
  ssl:
    key-store: classpath:certificate.p12
    key-store-password: EbBP[^{j`X~|j`x(
    key-store-type: PKCS12
    enabled: true

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://43.241.63.102:8888

  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**,/role/**,/authenticate,/validate,/refresh

        - id: MASTER-SERVICE
          uri: lb://MASTER-SERVICE
          predicates:
            - Path=/class/**,/region/**,/school/**,/educationalInstitution/**,/student/**

        - id: REPORT-SERVICE
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/report/**